### PR TITLE
added optional escape key for close clickery popover

### PR DESCRIPTION
**Pull request by kdrdgn**

### CODE REVIEW

**Comment by lecar-red** [comment]
Looks good, i'll merge it in today or tomorrow. Thanks for the contribution!

**Comment by kdrdgn** [comment]
you welcome, and thank you again for your popover improvements.

**Comment by lecar-red** [comment]
well there was a conflict with the merge but i was able to hand code in the changes.

**Comment by lecar-red** [comment]
please give it a test to make sure it works like yours does :)

**Pull request closed without merging**
